### ISSUE TITLE
pride update should also update git submodules

### ISSUE THREAD

**Issue by gnagy** [prezi/pride#125]

**Comment by lptr** [comment]
Try `pride update --recursive`. (Using `pride help update` is a good idea, too. :p)

You can also do

    pride config --global repo.recursive.always true

To set this to be the default behavior.

**Comment by gnagy** [comment]
Could we make this the built-in default behavour so it would work out of the box and then you'd need to do this instead to override?
pride config --global repo.recursive.always false 

Btw does this also work for pride add?

**Comment by lptr** [comment]
Yes, the `add` command uses the same code (`AddAction`) as `init`, so `repo.recursive.always` works the same way there, too. Please create a pull-reuqest if you want to change the default.
