### ISSUE TITLE
Make Pride available at plugins.gradle.org

### ISSUE THREAD

**Issue by punya** [prezi/pride#129]
This will enable Gradle 2.x users to use the new syntax

```gradle
plugins {
  id "com.prezi.pride" version "0.10"
}
```

Instructions are available at https://plugins.gradle.org/submit.

**Comment by lptr** [comment]
Hey, can you help me do this? A PR would be awesome. :)

**Comment by punya** [comment]
Yes, I'll work on it this weekend.

**Comment by lptr** [comment]
I took a look at this, and it was easy enough to do it all in one go. So I've renamed everything to `com.prezi.pride` -- I guess this will require the next release to be version `0.10`. I've already published the new plugin to Bintray, and now waiting for their approval to include my repository there in JCenter. I think we can close this pull-request now.

**Comment by lptr** [comment]
Please review the changes in master, and if you think they are okay, please close this PR.

**Comment by lptr** [comment]
Okay, so it appears that JCenter syncs Maven Central anyway, so the existing publishing to oss.sonatype.org should be enough. I've released 0.10, and it's already on Maven Central. Once it syncs to JCenter [here](http://jcenter.bintray.com/com/prezi/pride/), we can add the plugin to `plugins.gradle.org`.

**Comment by lptr** [comment]
For some reason the new group does not sync between Maven Central and JCenter. I've asked on Gradle forums about this (http://forums.gradle.org/gradle/topics/how-can-i-publish-my-plugin-to-plugins-gradle-org-from-maven-central), and also asked Bintray what to do about the sync problem.

**Comment by lptr** [comment]
It's now available: http://plugins.gradle.org/plugin/com.prezi.pride

**Comment by punya** [comment]
Thanks!
