### ISSUE TITLE
Upgrade to Gradle 2.3

### ISSUE THREAD

**Issue by coenwouters** [prezi/pride#144]

**Comment by lptr** [comment]
Hey there. Is this a requirement? I was not planning a release before Gradle 2.4 -- but then we are going to have some big news. If you really need a release before that, I can do it, but can you explain why you need this? You know that you can set the Gradle version Pride uses via `--gradle-version`, right?

**Comment by coenwouters** [comment]
We need Gradle 2.3 because of the improved eclipse-wtp plugin. 
However, we were not aware of that option for the pride init command. The use of the --gradle-version option solves this issue.
Thank you for you support.
