### ISSUE TITLE
Gradle 2.5 makes dynamicDependencies not necessary, can use normal syntax

### ISSUE THREAD

**Issue by jaysonminard** [prezi/pride#151]
See release notes, a specific mention of Prezi Pride about dynamicDependencies

https://docs.gradle.org/release-candidate/release-notes

**Comment by lptr** [comment]
Nice catch. :) Pride 0.11-rc-1 uses the new stuff. https://github.com/prezi/pride/tree/gradle-dependency-substitution branch for the code

**Comment by lptr** [comment]
You can download the RC from Releases

**Comment by jaysonminard** [comment]
a beta channel on brew would be very nice for the RC stuff (or just release it already jeje)

**Comment by lptr** [comment]
0.11 is out! Will talk to the prezi folks about including it in the Homebrew tap.
