### ISSUE TITLE
Would it be possible to update the brew formula, it, now, raises an error

### ISSUE THREAD

**Issue by fdagnat** [prezi/pride#162]
Error: Calling Formula.sha1 is disabled!
Use Formula.sha256 instead.
/usr/local/Homebrew/Library/Taps/lptr/homebrew-oss/pride.rb:7:in `<class:Pride>'
Please report this to the lptr/oss tap!

**Comment by rosadam** [comment]
The latest Homebrew (1.1.0) disabled SHA-1 checksum support: https://github.com/Homebrew/brew/releases/tag/1.1.0
@lptr can you update the pride formula to use sha256 instead?

**Comment by lptr** [comment]
I don't have access to the repo unfortunately. I'm planning to rework Pride with the new composite-build feature in Gradle, too. If only I had some time to do that. :)

**Comment by rosadam** [comment]
Changed the readme, so now the supported way to install is `brew install prezi/oss/pride` instead of `brew install lptr/oss/pride`. Also updated to sha256.

**Comment by fdagnat** [comment]
It does not work for me 

`brew install prezi/oss/pride`
`Updating Homebrew...`
`==> Tapping prezi/oss`
`Cloning into '/usr/local/Homebrew/Library/Taps/prezi/homebrew-oss'...`
`remote: Counting objects: 6, done.`
`remote: Compressing objects: 100% (6/6), done.`
`remote: Total 6 (delta 0), reused 4 (delta 0), pack-reused 0`
`Unpacking objects: 100% (6/6), done.`
`Error: Invalid formula: /usr/local/Homebrew/Library/Taps/prezi/homebrew-oss/fail.rb`
`Calling Formula.sha1 is disabled!`
`Use Formula.sha256 instead.`
...

**Comment by rosadam** [comment]
Untapping and tapping again resulted in the same error for me (without that installing worked fine).
I've updated all other formulae in the repo, so tapping `prezi/oss` works now.

**Comment by fdagnat** [comment]
ok worked like a charm
thank you
